---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matachLabels:
    app: nginx
  template: 
    metadata:
      labels:
      app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
        