---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 3
  selectoe:
    matachLabels:
    app: nginx
  template: 
    metadeta:
      labels:
      app:nginx
    spec:         
      containers:
        - name: nginx-container
          image: nginx
        